# apps/k8s/knarr/stack/nginx/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml # <-- Tells Kustomize to apply the file with the Service/Deployment