---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: media 
spec: # 2 spaces indent
  type: LoadBalancer
  ports: # 2 spaces indent
    - port: 80 # 4 spaces indent
      targetPort: 80 # 6 spaces indent
      protocol: TCP
      name: http
  selector: # 2 spaces indent
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: media
  labels:
    app: nginx
spec: # 2 spaces indent
  replicas: 1
  selector: # 2 spaces indent
    matchLabels:
      app: nginx
  template: # 2 spaces indent
    metadata:
      labels:
        app: nginx
    spec: # 4 spaces indent (This 'spec' is inside 'template')
      containers: # 6 spaces indent
        - name: nginx # 8 spaces indent
          image: nginx:latest
          ports:
            - containerPort: 80